# -*- coding: utf-8 -*-
"""i_got_that.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

x = str(input("What you gotta say? :"))
while x != "STOP" :
  x = str(input("I got that! Anything else? :"))
  if x == "STOP" :
    \
    break