# -*- coding: utf-8 -*-
"""age.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

my_age = 21+42
print(my_age)