# -*- coding: utf-8 -*-
"""whatsyourname.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

FN = input("Hey, what's your first name? :")
LN = input("And your last name? : ")
print(FN+' '+LN)