# -*- coding: utf-8 -*-
"""isneg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

num = float(input())
if num > 0 :
  print("This number is positive.")
elif num < 0 :
  print("This number is negative.")
else :
 print("This number is both positive and negative.")