# -*- coding: utf-8 -*-
"""password.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

password = "Python is awesome"
X = str(input())
if X == password :
  print("ACCESS GRANTED")
else :
  print("ACCESS DENIED.")