# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

print("Hello World")
