# -*- coding: utf-8 -*-
"""name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

first_name = "Pavarit"
last_name = "Vongkichpanit"
whole_name = first_name +"\t"+ last_name
print(whole_name)