# -*- coding: utf-8 -*-
"""multiplication_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

x = int(input("Enter a number :"))
i = int(0)
while i < 13:
  r = x*i
  print(i,"x",x,"=",r)
  i += 1