# -*- coding: utf-8 -*-
"""to25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eWW1xRv4k7wVpdgK5NWz1YVUM_yT80C
"""

x = int(input("Enter a number less than 25 :"))
if x > 25 :
  print("Error")
else :
 while x < 26:
  print("Inside the loop, my variable is",str(x))
  x += 1